<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.jeanbarcellos.project115</groupId>
    <artifactId>project115-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>project115-core-observability-spring</artifactId>
  <packaging>jar</packaging>

  <name>project115-core-observability-spring</name>
  <description>Biblioteca de Observabilidade</description>

  <properties>
    <!-- Java -->
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <!-- Dependências -->
    <spring-framework.version>6.2.17</spring-framework.version>
    <jackson.version>2.19.1</jackson.version>
    <jakarta.servlet-api.version>6.1.0</jakarta.servlet-api.version>
    <jakarta.persistence.version>3.2.0</jakarta.persistence.version>
  </properties>

  <dependencies>

    <!-- ******************************************************* -->
    <!-- DEPENDENCIAS DE COMPILACAO E RUNTIME                    -->
    <!-- ******************************************************* -->

    <!-- Lib project115-core-->
    <dependency>
      <groupId>com.jeanbarcellos.project115</groupId>
      <artifactId>project115-core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>

    <!-- Spring -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-autoconfigure</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
    </dependency>

    <!-- ******************************************************* -->
    <!-- DEPENDENCIAS DE TESTES                                  -->
    <!-- ******************************************************* -->

    <!-- JUnit -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Mocks -->
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Asserções -->
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

</project>