<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.jeanbarcellos.project115</groupId>
    <artifactId>project115-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>project115-core-quarkus</artifactId>
  <packaging>jar</packaging>

  <name>project115-core-quarkus</name>
  <description>Biblioteca compartilhada para microserviços Quarkus</description>

  <properties>
    <!-- Java -->
    <java.version>17</java.version>
    <maven.compiler.release>${java.version}</maven.compiler.release>
    <!-- Dependências -->
    <jakarta.ws.rs-api.version>4.0.0</jakarta.ws.rs-api.version>
    <jackson.version>2.19.1</jackson.version>
    <jakarta.validation-api.version>3.1.1</jakarta.validation-api.version>
    <jakarta.persistence-api.version>3.2.0</jakarta.persistence-api.version>
  </properties>

  <dependencies>

    <!-- ******************************************************* -->
    <!-- DEPENDENCIAS DE COMPILACAO E RUNTIME                    -->
    <!-- ******************************************************* -->

    <!-- Lib project115-core-->
    <dependency>
      <groupId>com.jeanbarcellos.project115</groupId>
      <artifactId>project115-core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>

    <!-- API Jakarta REST (JAX-RS) para exceções e contratos HTTP -->
    <dependency>
      <groupId>jakarta.ws.rs</groupId>
      <artifactId>jakarta.ws.rs-api</artifactId>
      <version>${jakarta.ws.rs-api.version}</version>
    </dependency>

    <!-- API Jakarta Validation para Bean Validation (@Valid, @NotNull, etc.) -->
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
      <version>${jakarta.validation-api.version}</version>
    </dependency>

    <!-- API Jakarta Persistence para exceções e contratos JPA -->
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <version>${jakarta.persistence-api.version}</version>
    </dependency>

    <!-- Jackson Core para parsing e processamento de JSON -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>${jackson.version}</version>
    </dependency>

    <!-- Jackson Databind para serialização e desserialização de objetos -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version}</version>
    </dependency>

    <!-- ******************************************************* -->
    <!-- DEPENDENCIAS DE TESTES                                  -->
    <!-- ******************************************************* -->

    <!-- JUnit -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Mocks -->
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Asserções -->
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

</project>