spring:
  application:
    name: project115-service-spring

  jackson:
    default-property-inclusion: non-null
    serialization:
      order-map-entries-by-keys: false
    mapper:
      sort-properties-alphabetically: false
